; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
; Ignora il file della ESP e compila il Main del Nano e i sensori
build_src_filter = +<*> -<main_ESP32.cpp> -<ESP32CAM.cpp>

lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    arduino-libraries/SD @ ^1.3.0



[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
; Compila tutto tranne il main del Nano e le librerie dei sensori
build_src_filter = +<*> -<main.cpp> -<BMP280.cpp> -<GPS_PA6H.cpp> -<MicroSD.cpp> -<MissionControl.cpp> -<MPU6050.cpp> -<Xbee_S2C.cpp>
; Velocità di comunicazione (fondamentale per i log della fotocamera)
monitor_speed = 115200
upload_speed = 115200
; --- GESTIONE MEMORIA (CRITICO) ---
; La libreria della camera è pesante. Usiamo una partizione che dia 
; più spazio al codice (App) sacrificando il sistema di aggiornamento via WiFi (OTA).
board_build.partitions = huge_app.csv
; --- LIBRERIE ---
; Solitamente la libreria per la camera è già nel framework, 
; ma potremmo aver bisogno di queste per gestire i sensori o la SD
lib_deps =
    esp32-camera
